# Generated by Django 4.0.3 on 2022-03-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFriends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='zip',
            field=models.CharField(default='32810', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
