# Generated by Django 4.0.3 on 2022-03-20 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMainPages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='main_page_for',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='object_id',
        ),
    ]
