# Generated by Django 4.0.3 on 2022-03-20 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myMainPages', '0002_remove_mainpage_main_page_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='main_page_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
