# Generated by Django 4.0.3 on 2022-03-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMainPages', '0003_mainpage_main_page_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='url',
            field=models.CharField(default='main', max_length=10),
            preserve_default=False,
        ),
    ]
