# Generated by Django 4.0.3 on 2022-03-20 01:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMainPages', '0004_mainpage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='main_page_for',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='url',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='side_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='hello'),
            preserve_default=False,
        ),
    ]
