# Generated by Django 4.0.3 on 2022-03-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMainPages', '0005_remove_mainpage_main_page_for_remove_mainpage_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='name',
            field=models.CharField(default='index', max_length=10),
            preserve_default=False,
        ),
    ]
